<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- Base Footprint para paquetes de navegacion -->
    <link name="base_footprint">
        <origin xyz="0 0 0" rpy="0 0 0"/>        
    </link>    
    
    <!-- Base Link del que se referencian el resto de elementos -->
    <link name ="base_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find ow_peque_description)/meshes/EnsamblajeRobotPeque.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 ${base_to_ground_height}" rpy="${pi / 2.0} 0 ${-2.0 * pi / 3.0}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="file://$(find ow_peque_description)/meshes/EnsamblajeRobotPeque.stl" scale="0.001 0.001 0.001"/>

                <!--cylinder radius="${base_radius}" length="${corner_height - corner_shaft_height }"/-->
            </geometry>
            <origin xyz="0 0 ${base_to_ground_height}" rpy="${pi / 2.0} 0 ${-2.0 * pi / 3.0}"/>
        </collision>
         <inertial>
            <mass value="5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0004055" ixy="0" ixz="0" iyy="0.0004055" iyz="0" izz="0"/>
        </inertial>
    </link>


    <xacro:macro name="omniwheel" params="prefix angle">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <mesh filename="file://$(find ow_peque_description)/meshes/RuedaOmnidireccional.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 ${pi / 2.0}"/>
                <material name="grey"/>
            </visual>
            <inertial>
                <mass value="0.582"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0005937" ixy="0" ixz="0" iyy="0.0005937" iyz="0" izz="0.0009841"/>
            </inertial>
            <collision>
                <geometry>
                    <!--mesh filename="file://$(find ow_peque_description)/meshes/omniwheel.stl" scale="0.001 0.001 0.001"/-->
                    <cylinder radius="${omniwheel_radius}" length="0.02"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
        </link>

        <joint name="base_${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <!-- Use 0 for the wheel joint z origin to match the other description
                 and avoid a 0 -> 0.05 jump in RViz when multiple descriptions
                 or TF sources are present. -->
            <origin xyz="${cos (angle) * base_radius} ${sin (angle) * base_radius} ${ground_to_shaft_height}" rpy="0 0 ${angle - pi / 2.0}"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:omniwheel prefix="front" angle="${pi / 2.0}"/>
    <xacro:omniwheel prefix="left" angle="${pi + pi / 6.0}"/>
    <xacro:omniwheel prefix="right" angle="${- pi / 6.0}"/>

    <!-- Joints -->

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${omniwheel_radius}" rpy="0 0 0"/>
    </joint>


</robot>
